CREATE USER SMC_USER IDENTIFIED BY SMC_USER;

GRANT CREATE SESSION TO SMC_USER;

CREATE TABLE A (A varchar2(10)) 

GRANT CREATE TABLE TO SMC_USER;

CREATE TABLESPACE smc
DATAFILE 'C:\ORACLEXE\APP\ORACLE\ORADATA\XE\smc.DBF' 
SIZE 2048M 
AUTOEXTEND ON 
NEXT 4M MAXSIZE UNLIMITED
LOGGING PERMANENT EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K 
SEGMENT SPACE MANAGEMENT MANUAL 
FLASHBACK ON;

ALTER USER SMC_USER
IDENTIFIED BY SMC_USER
DEFAULT TABLESPACE smc
quota unlimited on smc;

INSERT INTO A(A) VALUES ('ABCTEST');

DROP TABLE A;

